### ISSUE TITLE
Navigation not working

### ISSUE THREAD

**Issue by davidmarinangeli** [gastsail/JetExample#2]
I've just read your Medium article about Navigation with Compose but it does not seem to work. I'm doing this from my [HomeScreen](https://github.com/davidmarinangeli/Macaw/tree/master/app/src/main/java/com/david/voicememos/macaw/ui/home) and I'm using the Navigation you used, [this](https://github.com/davidmarinangeli/Macaw/tree/master/app/src/main/java/com/david/voicememos/macaw/ui/navigation)

Thanks 👍

**Comment by gastsail** [comment]
Hi @davidmarinangeli  , you forgot to setup the navigator 

Check: https://github.com/gastsail/JetExample/blob/master/jetpoll/src/main/java/com/example/jetpoll/ui/home/PollMain.kt

You are using just the action but instead you should first setup the navigator and then use the actions in your composables within that callback

Let me know if that solves your issue

**Comment by davidmarinangeli** [comment]
Thanks a lot for the help. I also changed and moved the `homeViewModel` call to the parent to prevent multiple calls when the composable re-renders.

Thanks a lot and great job!
